2025-05-20 08:43:05,736 - INFO - editor.py:45 - <module> - Editor session started. Logging initialized successfully.
2025-05-20 08:43:05,738 - INFO - editor.py:61 - <module> - Project root 'c:\Users\ahmad\OneDrive\Computer Files\Programming\Scripts\Github\Scripts\Python Scripts\Canvas Scripts\2024\Python Game\Platformer' setup in sys.path (from editor.py). Current sys.path[0]: c:\Users\ahmad\OneDrive\Computer Files\Programming\Scripts\Github\Scripts\Python Scripts\Canvas Scripts\2024\Python Game\Platformer
2025-05-20 08:43:05,778 - INFO - editor_assets.py:28 - <module> - EditorAssets: Imported 'resource_path' from root 'assets'.
2025-05-20 08:43:05,778 - WARNING - editor.py:78 - <module> - Relative import failed for editor modules: No module named 'editor_config'. Trying absolute (this may indicate a setup issue if it works)...
2025-05-20 08:43:05,779 - CRITICAL - editor.py:90 - <module> - Failed to import an editor-specific module (both relative and absolute): No module named 'editor_state'
Traceback (most recent call last):
  File "c:\Users\ahmad\OneDrive\Computer Files\Programming\Scripts\Github\Scripts\Python Scripts\Canvas Scripts\2024\Python Game\Platformer\editor\editor.py", line 70, in <module>
    from . import editor_assets
  File "c:\Users\ahmad\OneDrive\Computer Files\Programming\Scripts\Github\Scripts\Python Scripts\Canvas Scripts\2024\Python Game\Platformer\editor\editor_assets.py", line 37, in <module>
    import editor_config as ED_CONFIG
ModuleNotFoundError: No module named 'editor_config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\ahmad\OneDrive\Computer Files\Programming\Scripts\Github\Scripts\Python Scripts\Canvas Scripts\2024\Python Game\Platformer\editor\editor.py", line 81, in <module>
    from editor_state import EditorState
ModuleNotFoundError: No module named 'editor_state'
